# CUDA_VISIBLE_DEVICES=0,1 python3 -W ignore -m torch.distributed.launch --nnodes=1 --node_rank=0 --nproc_per_node=2 --use_env --master_port=1234 train.py --config configs/transibr_full.txt --expname transibr_gen_viewindependent_4layer_10srcviews_512rays_192points
# CUDA_VISIBLE_DEVICES=0,1 python3 -W ignore -m torch.distributed.launch --nnodes=1 --node_rank=0 --nproc_per_node=2 --use_env --master_port=1234 train.py --config configs/transibr_full.txt --expname transibr_gen_viewindependent_4layer_10srcviews_512rays_192points
# CUDA_VISIBLE_DEVICES=0,1 python3 -W ignore -m torch.distributed.launch --nnodes=1 --node_rank=0 --nproc_per_node=2 --use_env --master_port=1234 train.py --config configs/transibr_full.txt --expname transibr_gen_viewindependent_4layer_10srcviews_512rays_192points
# CUDA_VISIBLE_DEVICES=0,1 python3 -W ignore -m torch.distributed.launch --nnodes=1 --node_rank=0 --nproc_per_node=2 --use_env --master_port=1234 train.py --config configs/transibr_full.txt --expname transibr_gen_viewindependent_4layer_10srcviews_512rays_192points
# CUDA_VISIBLE_DEVICES=0,1 python3 -W ignore -m torch.distributed.launch --nnodes=1 --node_rank=0 --nproc_per_node=2 --use_env --master_port=1234 train.py --config configs/transibr_full.txt --expname transibr_gen_viewindependent_4layer_10srcviews_512rays_192points
# CUDA_VISIBLE_DEVICES=0,1 python3 -W ignore -m torch.distributed.launch --nnodes=1 --node_rank=0 --nproc_per_node=2 --use_env --master_port=1234 train.py --config configs/transibr_full.txt --expname transibr_gen_viewindependent_4layer_10srcviews_512rays_192points
# CUDA_VISIBLE_DEVICES=0,1 python3 -W ignore -m torch.distributed.launch --nnodes=1 --node_rank=0 --nproc_per_node=2 --use_env --master_port=1234 train.py --config configs/transibr_full.txt --expname transibr_gen_viewindependent_4layer_10srcviews_512rays_192points
# CUDA_VISIBLE_DEVICES=0,1 python3 -W ignore -m torch.distributed.launch --nnodes=1 --node_rank=0 --nproc_per_node=2 --use_env --master_port=1234 train.py --config configs/transibr_full.txt --expname transibr_gen_viewindependent_4layer_10srcviews_512rays_192points
# CUDA_VISIBLE_DEVICES=0,1 python3 -W ignore -m torch.distributed.launch --nnodes=1 --node_rank=0 --nproc_per_node=2 --use_env --master_port=1234 train.py --config configs/transibr_full.txt --expname transibr_gen_viewindependent_4layer_10srcviews_512rays_192points
# CUDA_VISIBLE_DEVICES=0,1 python3 -W ignore -m torch.distributed.launch --nnodes=1 --node_rank=0 --nproc_per_node=2 --use_env --master_port=1234 train.py --config configs/transibr_full.txt --expname transibr_gen_viewindependent_4layer_10srcviews_512rays_192points
# CUDA_VISIBLE_DEVICES=0,1 python3 -W ignore -m torch.distributed.launch --nnodes=1 --node_rank=0 --nproc_per_node=2 --use_env --master_port=1234 train.py --config configs/transibr_full.txt --expname transibr_gen_viewindependent_4layer_10srcviews_512rays_192points
# CUDA_VISIBLE_DEVICES=0,1 python3 -W ignore -m torch.distributed.launch --nnodes=1 --node_rank=0 --nproc_per_node=2 --use_env --master_port=1234 train.py --config configs/transibr_full.txt --expname transibr_gen_viewindependent_4layer_10srcviews_512rays_192points
# CUDA_VISIBLE_DEVICES=0,1 python3 -W ignore -m torch.distributed.launch --nnodes=1 --node_rank=0 --nproc_per_node=2 --use_env --master_port=1234 train.py --config configs/transibr_full.txt --expname transibr_gen_viewindependent_4layer_10srcviews_512rays_192points
# CUDA_VISIBLE_DEVICES=0,1 python3 -W ignore -m torch.distributed.launch --nnodes=1 --node_rank=0 --nproc_per_node=2 --use_env --master_port=1234 train.py --config configs/transibr_full.txt --expname transibr_gen_viewindependent_4layer_10srcviews_512rays_192points
# CUDA_VISIBLE_DEVICES=0,1 python3 -W ignore -m torch.distributed.launch --nnodes=1 --node_rank=0 --nproc_per_node=2 --use_env --master_port=1234 train.py --config configs/transibr_full.txt --expname transibr_gen_viewindependent_4layer_10srcviews_512rays_192points
# CUDA_VISIBLE_DEVICES=0,1 python3 -W ignore -m torch.distributed.launch --nnodes=1 --node_rank=0 --nproc_per_node=2 --use_env --master_port=1234 train.py --config configs/transibr_full.txt --expname transibr_gen_viewindependent_4layer_10srcviews_512rays_192points
# CUDA_VISIBLE_DEVICES=0,1 python3 -W ignore -m torch.distributed.launch --nnodes=1 --node_rank=0 --nproc_per_node=2 --use_env --master_port=1234 train.py --config configs/transibr_full.txt --expname transibr_gen_viewindependent_4layer_10srcviews_512rays_192points
# CUDA_VISIBLE_DEVICES=0,1 python3 -W ignore -m torch.distributed.launch --nnodes=1 --node_rank=0 --nproc_per_node=2 --use_env --master_port=1234 train.py --config configs/transibr_full.txt --expname transibr_gen_viewindependent_4layer_10srcviews_512rays_192points
# CUDA_VISIBLE_DEVICES=0,1 python3 -W ignore -m torch.distributed.launch --nnodes=1 --node_rank=0 --nproc_per_node=2 --use_env --master_port=1234 train.py --config configs/transibr_full.txt --expname transibr_gen_viewindependent_4layer_10srcviews_512rays_192points
# CUDA_VISIBLE_DEVICES=0,1 python3 -W ignore -m torch.distributed.launch --nnodes=1 --node_rank=0 --nproc_per_node=2 --use_env --master_port=1234 train.py --config configs/transibr_full.txt --expname transibr_gen_viewindependent_4layer_10srcviews_512rays_192points


# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train.py --config configs/transibr_full.txt --expname transibr_gnt_sam_ft_viewindependent --dinofield  --dino_dim 64 --folder_name SAM
# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train.py --config configs/transibr_full.txt --expname transibr_gnt_sam_ft_viewindependent --dinofield  --dino_dim 64 --folder_name SAM
# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train.py --config configs/transibr_full.txt --expname transibr_gnt_sam_ft_viewindependent --dinofield  --dino_dim 64 --folder_name SAM
# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train.py --config configs/transibr_full.txt --expname transibr_gnt_sam_ft_viewindependent --dinofield  --dino_dim 64 --folder_name SAM
# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train.py --config configs/transibr_full.txt --expname transibr_gnt_sam_ft_viewindependent --dinofield  --dino_dim 64 --folder_name SAM
# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train.py --config configs/transibr_full.txt --expname transibr_gnt_sam_ft_viewindependent --dinofield  --dino_dim 64 --folder_name SAM
# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train.py --config configs/transibr_full.txt --expname transibr_gnt_sam_ft_viewindependent --dinofield  --dino_dim 64 --folder_name SAM
# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train.py --config configs/transibr_full.txt --expname transibr_gnt_sam_ft_viewindependent --dinofield  --dino_dim 64 --folder_name SAM
# CUDA_VISIBLE_DEVICES=0 python3 -W ignore train.py --config configs/transibr_full.txt --expname transibr_gnt_sam_ft_viewindependent --dinofield  --dino_dim 64 --folder_name SAM

CUDA_VISIBLE_DEVICES=0 python3 -W ignore train.py --config configs/transibr_full.txt --expname gsn
