# CUDA_VISIBLE_DEVICES=0,1 python3 -W ignore -m torch.distributed.launch --nnodes=1 --node_rank=0 --nproc_per_node=2 --use_env --master_port=1234 train.py --config configs/transibr_full.txt --expname transibr_gnt_gen_expt --folder_name DiNOFeats
# CUDA_VISIBLE_DEVICES=0,1 python3 -W ignore -m torch.distributed.launch --nnodes=1 --node_rank=0 --nproc_per_node=2 --use_env --master_port=1234 train.py --config configs/transibr_full.txt --expname transibr_gnt_gen_expt --folder_name DiNOFeats
# CUDA_VISIBLE_DEVICES=0,1 python3 -W ignore -m torch.distributed.launch --nnodes=1 --node_rank=0 --nproc_per_node=2 --use_env --master_port=1234 train.py --config configs/transibr_full.txt --expname transibr_gnt_gen_expt --folder_name DiNOFeats
# CUDA_VISIBLE_DEVICES=0,1 python3 -W ignore -m torch.distributed.launch --nnodes=1 --node_rank=0 --nproc_per_node=2 --use_env --master_port=1234 train.py --config configs/transibr_full.txt --expname transibr_gnt_gen_expt --folder_name DiNOFeats
# CUDA_VISIBLE_DEVICES=0,1 python3 -W ignore -m torch.distributed.launch --nnodes=1 --node_rank=0 --nproc_per_node=2 --use_env --master_port=1234 train.py --config configs/transibr_full.txt --expname transibr_gnt_gen_expt --folder_name DiNOFeats
# CUDA_VISIBLE_DEVICES=0,1 python3 -W ignore -m torch.distributed.launch --nnodes=1 --node_rank=0 --nproc_per_node=2 --use_env --master_port=1234 train.py --config configs/transibr_full.txt --expname transibr_gnt_gen_expt --folder_name DiNOFeats
# CUDA_VISIBLE_DEVICES=0,1 python3 -W ignore -m torch.distributed.launch --nnodes=1 --node_rank=0 --nproc_per_node=2 --use_env --master_port=1234 train.py --config configs/transibr_full.txt --expname transibr_gnt_gen_expt --folder_name DiNOFeats
# CUDA_VISIBLE_DEVICES=0,1 python3 -W ignore -m torch.distributed.launch --nnodes=1 --node_rank=0 --nproc_per_node=2 --use_env --master_port=1234 train.py --config configs/transibr_full.txt --expname transibr_gnt_gen_expt --folder_name DiNOFeats
# CUDA_VISIBLE_DEVICES=0,1 python3 -W ignore -m torch.distributed.launch --nnodes=1 --node_rank=0 --nproc_per_node=2 --use_env --master_port=1234 train.py --config configs/transibr_full.txt --expname transibr_gnt_gen_expt --folder_name DiNOFeats
# CUDA_VISIBLE_DEVICES=0,1 python3 -W ignore -m torch.distributed.launch --nnodes=1 --node_rank=0 --nproc_per_node=2 --use_env --master_port=1234 train.py --config configs/transibr_full.txt --expname transibr_gnt_gen_expt --folder_name DiNOFeats
# CUDA_VISIBLE_DEVICES=0,1 python3 -W ignore -m torch.distributed.launch --nnodes=1 --node_rank=0 --nproc_per_node=2 --use_env --master_port=1234 train.py --config configs/transibr_full.txt --expname transibr_gnt_gen_expt --folder_name DiNOFeats
# CUDA_VISIBLE_DEVICES=0,1 python3 -W ignore -m torch.distributed.launch --nnodes=1 --node_rank=0 --nproc_per_node=2 --use_env --master_port=1234 train.py --config configs/transibr_full.txt --expname transibr_gnt_gen_expt --folder_name DiNOFeats
# CUDA_VISIBLE_DEVICES=0,1 python3 -W ignore -m torch.distributed.launch --nnodes=1 --node_rank=0 --nproc_per_node=2 --use_env --master_port=1234 train.py --config configs/transibr_full.txt --expname transibr_gnt_gen_expt --folder_name DiNOFeats
# CUDA_VISIBLE_DEVICES=0,1 python3 -W ignore -m torch.distributed.launch --nnodes=1 --node_rank=0 --nproc_per_node=2 --use_env --master_port=1234 train.py --config configs/transibr_full.txt --expname transibr_gnt_gen_expt --folder_name DiNOFeats
# CUDA_VISIBLE_DEVICES=0,1 python3 -W ignore -m torch.distributed.launch --nnodes=1 --node_rank=0 --nproc_per_node=2 --use_env --master_port=1234 train.py --config configs/transibr_full.txt --expname transibr_gnt_gen_expt --folder_name DiNOFeats
# CUDA_VISIBLE_DEVICES=0,1 python3 -W ignore -m torch.distributed.launch --nnodes=1 --node_rank=0 --nproc_per_node=2 --use_env --master_port=1234 train.py --config configs/transibr_full.txt --expname transibr_gnt_gen_expt --folder_name DiNOFeats
# CUDA_VISIBLE_DEVICES=0,1 python3 -W ignore -m torch.distributed.launch --nnodes=1 --node_rank=0 --nproc_per_node=2 --use_env --master_port=1234 train.py --config configs/transibr_full.txt --expname transibr_gnt_gen_expt --folder_name DiNOFeats
# CUDA_VISIBLE_DEVICES=0,1 python3 -W ignore -m torch.distributed.launch --nnodes=1 --node_rank=0 --nproc_per_node=2 --use_env --master_port=1234 train.py --config configs/transibr_full.txt --expname transibr_gnt_gen_expt --folder_name DiNOFeats
# CUDA_VISIBLE_DEVICES=0,1 python3 -W ignore -m torch.distributed.launch --nnodes=1 --node_rank=0 --nproc_per_node=2 --use_env --master_port=1234 train.py --config configs/transibr_full.txt --expname transibr_gnt_gen_expt --folder_name DiNOFeats
# CUDA_VISIBLE_DEVICES=0,1 python3 -W ignore -m torch.distributed.launch --nnodes=1 --node_rank=0 --nproc_per_node=2 --use_env --master_port=1234 train.py --config configs/transibr_full.txt --expname transibr_gnt_gen_expt --folder_name DiNOFeats

CUDA_VISIBLE_DEVICES=0,1 python3 -W ignore -m torch.distributed.launch --nnodes=1 --node_rank=0 --nproc_per_node=2 --use_env --master_port=1234 train.py --config configs/transibr_full.txt --expname transibr_gnt_dinov2_ft_viewindependent_512rays_trainall --dinofield  --dino_dim 64 --folder_name DiNOFeats_v2
CUDA_VISIBLE_DEVICES=0,1 python3 -W ignore -m torch.distributed.launch --nnodes=1 --node_rank=0 --nproc_per_node=2 --use_env --master_port=1234 train.py --config configs/transibr_full.txt --expname transibr_gnt_dinov2_ft_viewindependent_512rays_trainall --dinofield  --dino_dim 64 --folder_name DiNOFeats_v2
CUDA_VISIBLE_DEVICES=0,1 python3 -W ignore -m torch.distributed.launch --nnodes=1 --node_rank=0 --nproc_per_node=2 --use_env --master_port=1234 train.py --config configs/transibr_full.txt --expname transibr_gnt_dinov2_ft_viewindependent_512rays_trainall --dinofield  --dino_dim 64 --folder_name DiNOFeats_v2
CUDA_VISIBLE_DEVICES=0,1 python3 -W ignore -m torch.distributed.launch --nnodes=1 --node_rank=0 --nproc_per_node=2 --use_env --master_port=1234 train.py --config configs/transibr_full.txt --expname transibr_gnt_dinov2_ft_viewindependent_512rays_trainall --dinofield  --dino_dim 64 --folder_name DiNOFeats_v2
CUDA_VISIBLE_DEVICES=0,1 python3 -W ignore -m torch.distributed.launch --nnodes=1 --node_rank=0 --nproc_per_node=2 --use_env --master_port=1234 train.py --config configs/transibr_full.txt --expname transibr_gnt_dinov2_ft_viewindependent_512rays_trainall --dinofield  --dino_dim 64 --folder_name DiNOFeats_v2
CUDA_VISIBLE_DEVICES=0,1 python3 -W ignore -m torch.distributed.launch --nnodes=1 --node_rank=0 --nproc_per_node=2 --use_env --master_port=1234 train.py --config configs/transibr_full.txt --expname transibr_gnt_dinov2_ft_viewindependent_512rays_trainall --dinofield  --dino_dim 64 --folder_name DiNOFeats_v2
CUDA_VISIBLE_DEVICES=0,1 python3 -W ignore -m torch.distributed.launch --nnodes=1 --node_rank=0 --nproc_per_node=2 --use_env --master_port=1234 train.py --config configs/transibr_full.txt --expname transibr_gnt_dinov2_ft_viewindependent_512rays_trainall --dinofield  --dino_dim 64 --folder_name DiNOFeats_v2
CUDA_VISIBLE_DEVICES=0,1 python3 -W ignore -m torch.distributed.launch --nnodes=1 --node_rank=0 --nproc_per_node=2 --use_env --master_port=1234 train.py --config configs/transibr_full.txt --expname transibr_gnt_dinov2_ft_viewindependent_512rays_trainall --dinofield  --dino_dim 64 --folder_name DiNOFeats_v2
CUDA_VISIBLE_DEVICES=0,1 python3 -W ignore -m torch.distributed.launch --nnodes=1 --node_rank=0 --nproc_per_node=2 --use_env --master_port=1234 train.py --config configs/transibr_full.txt --expname transibr_gnt_dinov2_ft_viewindependent_512rays_trainall --dinofield  --dino_dim 64 --folder_name DiNOFeats_v2
CUDA_VISIBLE_DEVICES=0,1 python3 -W ignore -m torch.distributed.launch --nnodes=1 --node_rank=0 --nproc_per_node=2 --use_env --master_port=1234 train.py --config configs/transibr_full.txt --expname transibr_gnt_dinov2_ft_viewindependent_512rays_trainall --dinofield  --dino_dim 64 --folder_name DiNOFeats_v2
CUDA_VISIBLE_DEVICES=0,1 python3 -W ignore -m torch.distributed.launch --nnodes=1 --node_rank=0 --nproc_per_node=2 --use_env --master_port=1234 train.py --config configs/transibr_full.txt --expname transibr_gnt_dinov2_ft_viewindependent_512rays_trainall --dinofield  --dino_dim 64 --folder_name DiNOFeats_v2
